kind: pipeline
type: docker
name: Minecraft Vanilla Server

steps:
  - name: build public
    image: plugins/docker
    settings:
      repo: kimdrechsel/minecraft-vanilla-server
      username: kimdrechsel
      registry: docker.io
      password:
        from_secret: dockerhub_token
      dockerfile: ./Dockerfile
      tags:
        - latest
        - ${MINECRAFT_SERVER_VERSION}
      build_args_from_env:
        - MINECRAFT_SERVER_VERSION
        - DOWNLOAD_URL
    depends_on:
      - clone

trigger:
  event:
    - custom